### ISSUE TITLE
Add Currency Symbols

### ISSUE THREAD

**Issue by ccrvlh** [ccmars/world-data#1]
Hi,
Would be great to have currency symbols as well, lie US$, R$ or €.
Thanks!

**Comment by ccmars** [comment]
Those are available in the `world_currencies` table as decimal character codes and hexadecimal character codes in the `symbol_decimal` and `symbol_hex` columns respectively. Is that what you need?

> `[string]` **symbol_decimal**: Symbol of the currency in decimal [numeric character reference](https://en.wikipedia.org/wiki/Numeric_character_reference) codes, separated by semi-colons (;) if the symbol consists of multiple characters. For example, in HTML, turn the number `36` into `&#36;` to output a dollar symbol ($).

> `[string]` **symbol_hex**: Symbol of the currency in hexadecimal [numeric character reference](https://en.wikipedia.org/wiki/Numeric_character_reference) codes, separated by semi-colons (;) if the symbol consists of multiple characters. For example, in HTML, turn the string `0024` into `&#x0024;` to output a dollar symbol ($). To achieve the same in JavaScript, use `\u0024`, and in CSS, use `\0024`.

**Comment by ccrvlh** [comment]
@ccmars my apologies!
I missed the description on the readme, went straight to the data and couldn't find anything straightforward, this explains why...

Even though this data isn't supposed to change much, I wonder how have you been keeping this up to date? I would be happy to help also, this is pretty useful.

Cheers!

**Comment by ccmars** [comment]
Thanks, I'm glad you are finding it useful!

I update the data every year based on changes to the data by the ISO, but it does include some data that the ISO doesn't track. If you find anything out of date or missing, I'm happy to accept pull requests.
